SECodingChallenge.Web/Models/VehicleDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;

namespace SECodingChallenge.Web.Models
{
    public class VehicleDetail
    {
        public int DealerNumber { get; set; }
        public string CustomerName { get; set; }
        public string DealershipName { get; set; }
        public string Vehicle { get; set; }
        public double Price { get; set; }
        public DateTime Date { get; set; }

        public static VehicleDetail ConvertToModel(string line)
        {
            // https://stackoverflow.com/questions/18893390/splitting-on-comma-outside-quotes
            // with edge case tested
            var elements = Regex.Split(line, ",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");

            if (elements.Length != 6)
            {
                return null;
            }

            int dealerNumber;
            if (!int.TryParse(elements[0], out dealerNumber))
            {
                return null;
            }

            double price;
            if (!double.TryParse(elements[4].Replace("\"", ""), out price))
            {
                return null;
            }

            DateTime date;
            if (!DateTime.TryParse(elements[5], out date))
            {
                return null;
            }
            return new VehicleDetail() { DealerNumber = dealerNumber, CustomerName = elements[1], DealershipName = elements[2], Vehicle = elements[3], Price = price, Date = date };
        }
    }
}

SECodingChallenge.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SECodingChallenge.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SECodingChallenge.Web/Controllers/VisualizerController.cs
using SECodingChallenge.Web.Helpers;
using SECodingChallenge.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SECodingChallenge.Web.Controllers
{
    public class VisualizerController : Controller
    {
        [HttpGet]        
        public async Task<ActionResult> Index()
        {
            try
            {                
                return View("Index");
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;                
                return View("Error");
            }
        }

        [HttpPost]
        public async Task<ActionResult> ViewSalesData()
        {
            try
            {
                HttpPostedFileBase salesDataFile = Request.Files.Count > 0 ? Request.Files[0] : null;
                IList<string> csvData = CSVHelper.ReadCSVFile(salesDataFile);

                if (csvData == null)
                {
                    ViewBag.Errors = new[] { "Unable to read CSV file." };
                }
                IList<VehicleDetail> vehicleDetails = CSVHelper.ConvertToModel(csvData);
                ViewBag.MostSoldVehicle = vehicleDetails.GroupBy(vd => vd.Vehicle).GetHighesCountGroup();
                return View("Results", vehicleDetails);
            }
            catch (Exception ex)
            {
                Response.StatusCode = 500;
                return View("Error");
            }
        }
    }
}

SECodingChallenge.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <p class="lead">Click on visualize button from top to upload file and visualize sale's data.</p>    
</div>

SECodingChallenge.Web/Views/Shared/ErrorDisplay.cshtml
@{
    Layout = null;
}
OOPS! SOMETHING WENT WRONG. PLEASE TRY AGAIN!

SECodingChallenge.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sale's Data Visualizer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Data Visualizer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Visualize", "Index", "visualizer")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sale's Data Visualizer</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("CustomJs", false)
</body>
</html>

SECodingChallenge.Web/Views/Visualizer/Index.cshtml
@{
    ViewBag.Title = "Visualize Sale's Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bridge-lightpurple brdg-subbar">
            <h2>Visualize Sale's Data</h2>
        </div>
    </div>
</div>
@using (Html.BeginForm("ViewSalesData", "Visualizer", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="container brgd-container">
        <p class="brdg-requiredfields">
            <span class="bridge-pink-text">*</span> Required fields
        </p>
        <div class="row">
            <div class="col-lg-12 brdg-addnew-resident-form-int brdg-changepss-container">
                <div class="brdg-changepss">                    
                    <div class="bridge-form-medium brdg-addnew-resident-form-int bridge-form-textfield1 bridge-select-greylabel">
                        <label for="upload">Sales Data File: <span class="bridge-pink-text bridge-fonts-bold">*</span></label>
                        <input type="file" id="upload" name="upload">
                    </div>

                    <div class="bridge-submitbutton brdg-changepss-btn">
                        <input value="Upload File" type="submit" id="submitButton" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

SECodingChallenge.Web/Views/Visualizer/Results.cshtml
@using SECodingChallenge.Web.Models;

@{
    ViewBag.Title = "Visualize Sale's Data";
Layout = "~/Views/Shared/_Layout.cshtml";
var vehicleDetails = (IList<VehicleDetail>)Model;

var noResultsFoundMessageFound = ViewBag.NoResultsFoundMessage;
var mostSoldVehicle  = ViewBag.MostSoldVehicle;
}

<div class="container">
    @if (vehicleDetails?.Count() > 0)
    {
        <h4>Most sold vehicle : @mostSoldVehicle</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Number</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Dealership</th>
                    <th scope="col">Vehicle</th>
                    <th scope="col">Price</th>
                    <th scope="col">Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var vehicleDetail in vehicleDetails)
                {
                <tr>
                    <td>
                        @vehicleDetail.DealerNumber
                    </td>
                    <td>
                        @vehicleDetail.CustomerName
                    </td>
                    <td>
                        @vehicleDetail.DealershipName
                    </td>
                    <td>
                        @vehicleDetail.Vehicle
                    </td>
                    <td>
                        @string.Format("{0:C}", vehicleDetail.Price)
                    </td>
                    <td>
                        @vehicleDetail.Date.ToString("MM/dd/yyyy")
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h6>No results found</h6>
    }
</div>